//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AG04.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblMemberSkills
    {
        public int SkillID { get; set; }
        public int MemberID { get; set; }
        public string Name { get; set; }
        
        [StringLength(10, ErrorMessage ="Level must be between 3 and 10!", MinimumLength = (3))]
        public string SkillLevel { get; set; }
    
        public virtual tblMember tblMember { get; set; }
    }
}
